name: Build

on:
    push:
        branches:
            - "**"
    pull_request:

permissions:
    contents: read
    checks: write

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
            - name: Install dependencies
              run: npm ci
            - name: Build app
              run: npm run build
